### ISSUE TITLE
Show/hide toggle on small screens to hide the trending tags on FastFT

### ISSUE THREAD

**Issue by bjfletcher** [Financial-Times/next-stream-page#1023]
The first bit of React work is nice and simple, we need to display a show/hide toggle on small screens to hide the _trending_ tags sections of FastFT.

The requirement being that when a user visits FastFT (https://next.ft.com/fastft) that there may be no content displayed without scrolling down a fair bit.

<img width="348" alt="screen shot 2016-04-14 at 12 26 33" src="https://cloud.githubusercontent.com/assets/733849/14531565/c7ffbeb2-0255-11e6-83e3-1efe826901e1.png">

**Comment by bjfletcher** [comment]
@i-like-robots Did you say you've got a design for this?

**Comment by i-like-robots** [comment]
Yes! Here they are: https://drive.google.com/a/ft.com/folderview?id=0B1gNpLmbV3hqRU5fdWRGMFF6Qmc
