### ISSUE TITLE
Improve performance of Special Reports

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#1032]
The special reports home page regularly times out locally, on CI and in production. We need to look at ways to optimise this Elasticsearch query: https://github.com/Financial-Times/next-stream-page/blob/master/server/controllers/shared/special-reports.js

**Comment by matthew-andrews** [comment]
if you didn't want to optimise it, we could put it into `next-es-interface` and then consume it via fastly  with a `stale-while-revalidate` header (effectively putting a cache in)
