### ISSUE TITLE
Merge article-like models into the main article model

### ISSUE THREAD

**Issue by sumeetadur** [Financial-Times/next-stream-page#1033]
Article model:
https://github.com/Financial-Times/next-stream-page/blob/master/server/models/article.js

Article-like models:
- Stickies (https://github.com/Financial-Times/next-stream-page/blob/master/server/transforms/stickies.js#L71)
- Featured Content (https://github.com/Financial-Times/next-stream-page/blob/master/server/transforms/featured-content.js#L74)

**Comment by andygnewman** [comment]
Stickies & Featured Content are no more, so closing this issue.
