### ISSUE TITLE
Remove special /special-report URL

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-stream-page#1066]
[Make consistent with other stream URLs ` /stream/specialReportId/{{tmeId}}` would really make vanity url support simple + tidier

**Comment by matthew-andrews** [comment]
https://next.ft.com/stream/specialReportsId/YTBhOTYzYTUtMzdhMi00OTk3LWJjZDUtOGM2M2Y2ZTI2MjYy-U3BlY2lhbFJlcG9ydHM=

instead of

https://next.ft.com/special-reports/YTBhOTYzYTUtMzdhMi00OTk3LWJjZDUtOGM2M2Y2ZTI2MjYy-U3BlY2lhbFJlcG9ydHM=

**Comment by TheoLeanse** [comment]
![](http://i.telegraph.co.uk/multimedia/archive/02629/BAYEAUX_2629155b.jpg)
