### ISSUE TITLE
Spike Preact for the client side

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#1129]
- [ ] Switch from `React.createClass` to ES6 class or functional components
- [ ] Remove react-redux, just use vanilla contexts
- [ ] Add preact and preact-compat to dependencies
  ...

**Comment by matthew-andrews** [comment]
💚

**Comment by i-like-robots** [comment]
Tracking https://github.com/i-like-robots/react-tags/issues/19

**Comment by i-like-robots** [comment]
No longer relevant, closing.
