### ISSUE TITLE
Improve layout structure of stream list

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-stream-page#1280]
At L breakpoint, the original design was for 8 cols stream list, 4 cols for ad / trending topics.

To improve space for the stream list, some styling overrides were done to reduce the 4 cols down to an effective 316px.

However this caused some issues because the override was of equal specificity as the original styling and didn't always take precedence.

This was quickly overcome by adding an element selector to the override.

However this is not the best long term solution and should be readdressed.

**Comment by bjfletcher** [comment]
I think the solution you have now put in (overriding grid instead of increasing specificity) is ok.

**Comment by andygnewman** [comment]
My point was not related to the solution for improving the overriding, but the fact that if we're overriding the grid, we probably shouldn't be using the grid in the first place.

**Comment by bjfletcher** [comment]
@andygnewman I think we should continue and use `o-grid` on the page, just for those two particular columns on L and XL need it a bit different. I think it's reasonable to use `o-grid` and override where appropriate.
