### ISSUE TITLE
Scenario: Try to find a journalist via stream

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-stream-page#545]
Scenario: I want to follow a specific journalist. 
 * I can't recall the journalist's name but I know I'll recognise it.
 * I know he writes for FT Alphaville.

First, I go to http://next.ft.com/myft/my-topics, and under "Follow more", enter "FT Alphaville".
![image](https://cloud.githubusercontent.com/assets/224547/8204463/b6abdf1e-14e0-11e5-9381-a4fbdb898f7a.png)

(Note: this would be a good place to list related data like journalists — based on the search results)

Then I click "FT Alphaville" to go to that stream. 
![image](https://cloud.githubusercontent.com/assets/224547/8204511/0d4a1ef8-14e1-11e5-9df1-973110076161.png)

Two possible improvements: 
 1. Add journalists' author links to each article row;
 2. Remove all of the "FT Alphaville" from each article row. 

I'm not married to the latter but the former would be useful.

**Comment by matthew-andrews** [comment]
Quite keen to keep the logic for that tag simple though and I suspect (although this is definitely a question for UX! — @adamsilver @Jesslipson?) putting the author there, although in this case would have been useful to you, is probably, overall, less useful in the general case.

Hmm… an improvement could be to not allow our primary-tag-picking-logic to pick the same tag as the stream page the user is on…… at least there would be more variety / usefulness of that data……  (This way it would be _more likely_ an author name would appear there)

One idea could be a “who writes for” module…… a bit like the sidebar on www.ft.com/fastft, except generated by metadata (automatically show the most prolific (or perhaps even better most popular based on Spoor data cc @commuterjoy) authors for any given stream.

**Comment by adamsilver** [comment]
Happy to having a meeting to discuss the problem and potential solutions. @matthew-andrews

**Comment by adambraimbridge** [comment]
Thanks @matthew-andrews — I like the idea to "not allow our primary-tag-picking-logic to pick the same tag as the stream page the user is on".

**Comment by matthew-andrews** [comment]
^^ it doesn't actually solve your problem but i think will make the stream more useful @adambraimbridge
