### ISSUE TITLE
Open Article in Stream - Potential Approaches (pro's / con's / discussion)

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-stream-page#820]
A requirement of FastFT is to open posts (which in next are a type of content like an article) within the stream and not go to another page.

Possible methods;

## iFrame

| Advantages | Challenges to resolve |
|---|---|
| Simple to implement | media queries react to size of iFrame, eg. tablet within desktop |
| Styles live in one place - Article | Accessibility issues | 
| Actions in article tracked as an article (RFV etc) | managing links within iFrames |

## HTML

| Advantages | Challenges to resolve |
|---|---|
| Overcomes iFrame challenges | Styling - duplication vs article? |
| Separation of concerns | What tracking does an article in stream need? |

Further comments etc. welcome

**Comment by matthew-andrews** [comment]
i think this is solved now?

**Comment by andygnewman** [comment]
Closed - HTML solution adopted
