### ISSUE TITLE
single taxonomy controller

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#839]
I don't believe there is any value in maintaining 3 taxonomy controllers:

- v1-taxonomy.js
- v1-v2-taxonomy.js
- v2-taxonomy.js

These should be refactored into a single controller with full spec.

**Comment by matthew-andrews** [comment]
i want to back away from some of our integrations with CAPI V2…  e.g. stop serving responses on `/organisation/uuid` and `/people/uuid` endpoints … use the usual tme id endpoints instead … and reduce the number of redirects we have over there.

**Comment by i-like-robots** [comment]
:+1:

**Comment by callumlocke** [comment]
There are only 3 thing-types that are handled by special controllers:

- `/people/:id` (`v1-v2-taxonomy.js`)
- `/organisations/:id` (`v1-v2-taxonomy.js`)
- `/brands/:id` (`v2-taxonomy.js`)

Everything else goes through the v1-taxonomy controller.

What would it mean to "stop serving responses" on those endpoints (beyond simply removing those three routes and deleting those controllers)? Would we need to make corresponding changes in other apps or is this a content issue? For example, links for "Mark Carney" throughout the site currently point to `/people/843f6641-22a8-3163-aa9d-b70909b46a83` – how would this get changed? Sorry I'm completely new to this...

**Comment by matthew-andrews** [comment]
@callumlocke those are CAPI V2-style URLs, for each of them there is a CAPI V1 equivalent.  We originally pushed people through to the V2-style ones to be future proof… but the new metadata system didn't come as quickly as we thought it would…

In order to convert the old URLs we have to do a lot of redirecting back and forth…  That could be greatly simplified (and then ultimately moved to `next-redirector`) if we went back to using

`/stream/peopleId/TMEID`,`/stream/organisationId/TMEID`

The `/brand/` URLs are basically unused now.

**Comment by callumlocke** [comment]
so can we just do this

```js
app.get('/people/:thingId', (req, res) => res.redirect('/peopleId/' + uuid2tmeid(req.params.thingId)))
app.get('/organisations/:thingId', (req, res) => res.redirect('/organisationsId/' + uuid2tmeid(req.params.thingId)))
```

...and delete the v2 controllers?

And is `function uuid2tmeid(uuid) {}` actually possible? I'm not clear on what a TMEID contains

**Comment by matthew-andrews** [comment]
not quite so easy…  for `organisation` endpoints there are some features that would need to be ported over…  e.g. https://next.ft.com/organisations/ccaa202e-3d27-3b75-b2f2-261cf5038a1f (look at the header — although maybe Max will let us kill that feature……)  for people it could be that simple.
also i think the redirection logic _ought_ to live in `next-redirector`.

uuid2tmeid is possible but requires an API lookup:-

http://api.ft.com/concordances?conceptId=http://api.ft.com/things/ccaa202e-3d27-3b75-b2f2-261cf5038a1f?apiKey=???

**Comment by callumlocke** [comment]
ah, is what's going on [here](https://github.com/Financial-Times/next-stream-page/blob/52bedee1e46fb488cc35ee0235c56c57510b40ed/server/controllers/v1-taxonomy.js#L49-L52) something similar? (special treatment of peopleId and organisationsId)

**Comment by matthew-andrews** [comment]
yes that would be removed once we go back to using TME based URLs for orgs/peeps

**Comment by i-like-robots** [comment]
We should be moving all streams over to the new architecture over the next few weeks. We need to decide how we should handle v2 streams: whether we redirect to the equiv. v1 URL or not.

**Comment by matthew-andrews** [comment]
are there any v2 streams that we care about that don't have equivalent v1 id's?

**Comment by i-like-robots** [comment]
Not that I am aware of.

I think the only thing stopping this happening is the last point in https://github.com/Financial-Times/next-stream-page/issues/839 which we still need to decide whether or not is worth keeping (IMO delete it and bring it back when we have a proper plan for it all).

**Comment by matthew-andrews** [comment]
i'd support that.

**Comment by i-like-robots** [comment]
This is happening

https://github.com/Financial-Times/next-stream-page/issues/987
https://github.com/Financial-Times/next-stream-page/issues/988
