### ISSUE TITLE
Content management

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#843]
We have pressures from several teams - blogs, editorial and IG - to provide some kind of content management and curation functionality to streams. 

We have been given a project to pull the widgets used by FT blogs into blog stream pages but I'd like to see this brief relaxed to become a more generic feature useful to all the teams mentioned above.

Secondly, we have configurations for different stream types that are currently managed manually. We are aware that this is only manageable for a small number of streams and that turning features on or off at short notice is not always possible as it requires development effort. 

What I propose is a simple, drop-in admin to handle predefined content sections and stream configuration. I believe we can please a lot of people by simply providing one or two free text areas and widgets such as pinned stories.

This admin area could be exposed to a set of users in the front end as a basic 'edit' link that directs them to the admin page for that stream.

Storing the configuration, HTML content/widget data in an Elasticsearch index would be just fine. There's no sensitive information, we can fit the data into a single structure, we would read more than than write and we can get all the information with a single document request:

```
{
    "id": "streamId",
    "config": [
        {
            "name": "liveUpdates",
            "value": true
        },
        {
            "name": "hotTopics",
            "value": false
        },
        {
            "name": "facetted",
            "name": true
        }
    ],
    "content": [
        {
            "name": "aside",
            "type": "html",
            "body": "<p>Meet our editor...</p>",
        },
        {
            "name": "top",
            "type": "list",
            "body": [
                "bba1e8f0-ba81-11e5-bf7e-8a339b6f2164",
                "9660222e-9578-3ac5-8211-2251c9ca6345"
            ]
        }
    ]
}
```

Next doesn't get a lot of love downstairs, maybe this could tempt some people over?

I have some previous with this, we had something very similar at a previous employer to manage curate and manage certain streams (though we called them 'stacks').

**Comment by i-like-robots** [comment]
Just sharing some thoughts after yesterdays meetings @matthew-andrews @kavanagh @andygnewman

**Comment by kavanagh** [comment]
Interesting. Cc @callumlocke.

My quick first reaction is: there sounds like there are some neat ideas here but also sounds brave.

Although I think Sticky stories (aka 'best of', 'editors picks', 'top stories' or 'featured') is useful I dont know how they work in the context of the  page yet.. eg are they more important than the very latest news?

So might this kind of customisation be too early? Giving the impression you can 'edit' the page may be a slippery slope to preditor page style functionality which is flexible at the cost of slowing change?

I dont know about the needs of other teams but perhaps the way IG is working on augmenting one or two specific streams to understand the reader and editorial needs could be a pattern for exploration. Build for use, refactor for reuse.

A json object just for storing the on off state of stream page features, per stream, may simplify some of the code. I hazard that needs are not well understood.

**Comment by matthew-andrews** [comment]
Would prefer if we can keep the different types of stream metadata in separate indexes (shouldn't add too much overhead if they're all got through `mgets`).  Hopefully this will help us in the future move the responsibility to maintaining this stuff out of the Next team and also keep things decoupled from each other.  There will almost certainly be use cases for these sorts of things beyond streams.  Advert config springs to mind…  Also some of the above object are already available in other FT APIs.

**Config**
```
    "id": "streamId",
    "config": [
        {
            "name": "liveUpdates",
            "value": true
        },
        {
            "name": "hotTopics",
            "value": false
        },
        {
            "name": "facetted",
            "name": true
        }
    ],
```
E.g. one stream switches index that has the ‘config’ part of that object.

**Lists**
```
            "name": "top",
            "type": "list",
            "body": [
                "bba1e8f0-ba81-11e5-bf7e-8a339b6f2164",
                "9660222e-9578-3ac5-8211-2251c9ca6345"
            ]
```

The list part for example would almost certainly be provided by the lists' content API.  It might be valuable for Next's ES to provide a cache of this but I think we should copy the API contract from over there and, at least as an MVP, initially just use the Content API directly for this one…

**Content**

```
{
            "name": "aside",
            "type": "html",
            "body": "<p>Meet our editor...</p>",
        },
```

It may be that this content will be available through the Content API (Dan mention this might go under a new `/brands` endpoint…)  Again there might be value in having this mirrored by ES, but again I feel that should be as true a mirror as possible — not a new API contract that we invent…

**Comment by matthew-andrews** [comment]
also bear in mind ES is **NOT** backed up so we would need to solve that.

**Comment by kavanagh** [comment]
Ultimately this general idea sounds like a maturity from Bertha sheets – a good thing IMO.

**Comment by kavanagh** [comment]
Also I agree with Matt about splitting it out into separate bits.

**Comment by commuterjoy** [comment]
The functionality sounds useful.

Two thoughts ...

--

Most streams are automated, and I think the future of streams/homepage/more-ons will be greater automation/personalisation (directed by editorial, stats etc.), so I like the idea of providing a structure for managing that - config api*, and lists built as APIs feed in to *help* decide what the user sees. I'd stay away from wysiwyg.

* btw, Guardian used s3 for this sort of thing.

--

> drop-in admin to handle defined content sections

I'm less convinced of providing CMS for ad-hoc content and changes to streams, but I perhaps don't understand the use cases, but I'd hope the Content API or Blogs API team could pick up anything like author biogs, or additional fields in articles to assist in promotion. It sounds like you are talking about people cutting and pasting bits of HTML in to your system?

**Comment by andygnewman** [comment]
I'm going to suggest we close this issue as streams have progressed considerably (along these lines) in the last 10 months.

eg. 
- top stories is available for every stream by editorial control
- for brands and author taxonomies, editorial can control subheader content
- custom fragments (eg. brexit, US election) can be added to any page
