### ISSUE TITLE
Odd open in stream scroll repositioning

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-stream-page#850]
I had the *EXACT* problem when I tried to implement this before.

![odd scrolling](https://cloud.githubusercontent.com/assets/825088/12358664/4f9905be-bba6-11e5-8763-1a8e0ad797f4.gif)

**Comment by andygnewman** [comment]
Scroll positioning when I close on iPhone works as expected.

**Comment by i-like-robots** [comment]
Does this depend on how far down the page you are and the amount of content below the viewport? Might solve itself when we get a huge footer =P

**Comment by i-like-robots** [comment]
This was catered for when released I think (@andygnewman?)

**Comment by andygnewman** [comment]
Yes, all done.
