### ISSUE TITLE
Webkit focus ring appears around stream container

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-stream-page#867]
To reproduce: click somewhere inside the stream container

![image](https://cloud.githubusercontent.com/assets/250617/12515557/e374814e-c120-11e5-9d1d-f942e775e697.png)

I think it's due to the `div.stream__container` element having the attribute `tabindex="-1"`.

The value `-1` is supposed to make it not possible to tab to the element (not sure why this would be needed as it's a div so should be un-tabbable anyway?)... but strangely it still makes the element appear focused when clicked. This might even be a bug in webkit/blink

**Comment by i-like-robots** [comment]
Fixed in 01c96ddf9b750b987434752f6088077ac769d0de
