### ISSUE TITLE
Can we make each stream item be an o-grid-container, instead of just the whole stream?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-stream-page#888]
For the custom Brexit page, we're hoping to be able to make one of our custom stream items have a different background colour that extends all the way to the left and right edges of the viewport. Currently this isn't possible in snappy layouts (M and above) because the whole stream is an `o-grid-container`.

I want to know if it's OK for me to change this – i.e. to remove the `o-grid-container` class from the stream container, and modify the various stream item components so that each one includes its own `o-grid-container` wrapper if it needs one.

Aside from the specific design I'm trying to build, I think this change is probably a good idea anyway, as it would give more freedom in what kind of things custom stream items can do.

I've tried making the necessary changes locally and it seems to work fine, but since it modifies a bunch of component files outside my purview I thought I'd better ask what everyone thinks?

@andygnewman @ironsidevsquincy @matthew-andrews @i-like-robots

**Comment by matthew-andrews** [comment]
I'm not an expert on o-grid but I thought you could next o-grids?

**Comment by matthew-andrews** [comment]
Could you link to the design you're building to?  I'm having a hard time visualising what the problem is and how this solves it…

**Comment by callumlocke** [comment]
This is not a finished design but it illustrates the point well:

![image](https://cloud.githubusercontent.com/assets/250617/12766772/293a4990-c9fd-11e5-94c4-c027e61a714b.png)

The row of featured articles is a custom stream item that gets spliced into the stream array (in exactly the same way as photo diary, hot topics, etc).

The problem is there's no way to make the darker pink extend all the way to the left and right of the viewport, because the whole stream is one big `o-grid-container`.

What I'm suggesting would mean there's an `o-grid-container` inside every stream item instead.

**Comment by andygnewman** [comment]
Can you get your designer to talk to us about this. Conscious that streams haven't had much in the way of design treatment recently and would be good to understand whether this is just a one off use case or something we'd look to adopt on other non-stream item things like photo diary etc.

**Comment by matthew-andrews** [comment]
Just remembered we have this sort of thing on the article pages already (background colour bleeding to the edge).  So this design style is still within Next but I support Andy…  Before we add the flexibility of doing this in more than one component we should make sure we want to do this in more than one component…  And if the design team don't want to do it anywhere else we probably shouldn't do it on this page…

This shouldn't block you should it @callumlocke?  The featured article component can be continue to be built without the bleeding for now?

**Comment by i-like-robots** [comment]
_Ideally_ a component such as a stream item should have as few layout opinions as possible, I think they should just naturally fit their container. This is on my mind because we're due to abstract the stream and stream items out to be used within other applications.

I also think the treatment should be consistent between streams as @matthew-andrews mentions. If it's decided the unique treatment is required then I think either create a unique page template (maybe that would make your life easier anyway?) or I think it can be done with CSS alone: http://codepen.io/anon/pen/adaoRQ

**Comment by callumlocke** [comment]
> (nesting containers compounds min/max width)

OK I see it would end up with nested containers if you abstracted them and used them elsewhere. Unless the item container-ing was configurable somehow

> or it can be done with CSS alone: http://codepen.io/anon/pen/adaoRQ

that's neat, I'll give that a go
