### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#893]
## Content

- [ ] Images with no alt text should have blank alt text attribute to prevent screen readers trying to interpret file name
- [ ] Stream item tags are marked up as a list. Because they're not actually list it adds a lot of extra noise
- [x] ~~Duplicated H1 at bottom of page should not be a heading as it has no content~~
- [x] Fast FT branded header lacks contrast

## Widgets

- [x] Pagination next/prev links need title attribute (to read 'next page' and 'previous page') or label

**Comment by andygnewman** [comment]
@i-like-robots I think we can close this one now as the alt text is handled by n-image and the tags issue was from an old design.

**Comment by i-like-robots** [comment]
okidoke.

We're long due some re-testing anyway
