### ISSUE TITLE
Migration to transforms

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#903]
I think these are the key features that must be migrated so that we can run all tag based streams from a single controller.

- [x] Remove CAPI v2 streams (https://github.com/Financial-Times/next-stream-page/pull/919)
- [x] Migrate photo diary to transform
- [x] Migrate hot topics/hot opinion/hot analysis to transform
- [x] Migrate related tags to transform
- [x] Migrate podcast latest/podcast hub to transform https://github.com/Financial-Times/next-stream-page/pull/989 + https://github.com/Financial-Times/next-stream-page/pull/990 
- [x] Migrate news feed to transform (https://github.com/Financial-Times/next-stream-page/pull/908)
- [x] Organisations/people ~~FactSet/~~Markets data https://github.com/Financial-Times/next-stream-page/pull/992

**Comment by callumlocke** [comment]
Do you think these migrations should be done before or after reorganising the component files into `(server|client|shared)/components` (https://github.com/Financial-Times/next-stream-page/issues/868#issuecomment-175688374)? Or kind of at the same time?

**Comment by i-like-robots** [comment]
No opinion!

**Comment by callumlocke** [comment]
ok I've done a big reorganise here anyway: https://github.com/Financial-Times/next-stream-page/pull/924

**Comment by matthew-andrews** [comment]
I think also need to kill the `v1-v2` controller stream ^^

**Comment by matthew-andrews** [comment]
:tada:
