### ISSUE TITLE
Brexit stream card doesn't scroll you when it expands

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-stream-page#920]
1. Go to https://next.ft.com/stream/topicsId/NDdiMzAyNzctMTRlMy00Zjk1LWEyZjYtYmYwZWIwYWU2NzAy-VG9waWNz on a small screen
2. Tap the "Show full referendum guide" to trigger o-expander

Expected: page should scroll you down a bit so you're now looking at the expanded content

Actual: most of the expanded content appears outside the viewport, and it feels wrong

---

notes

Apparently the FastFT o-expanders have some logic to scroll you down automatically. Currently the brexit metacard's expansion is powered by a global `oExpander.init()` call [here](https://github.com/Financial-Times/next-stream-page/blob/e071bee7de58be8f6de91a96942943db7c75795c/client/main.js#L39) in next-stream-page (i.e. it's not done by the [brexit metacard fragment](https://github.com/ft-interactive/brexit-stream-content) itself, which has no javascript). So I'm not sure what the best way to solve this is, as setting up auto-scrolling for *any* o-expander component on the page (including any that might be added in future) might be problematic

**Comment by callumlocke** [comment]
think this should be done in o-expander.

opened here: https://github.com/Financial-Times/o-expander/issues/27

**Comment by andygnewman** [comment]
Closing this as solution seems to be in different repo.
