### ISSUE TITLE
Determine output format by query string rather than suffix

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-stream-page#930]
It'll help us simplify how we do vanity URLs.

https://next.ft.com/stream/brandId/NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz.rss
=>
https://next.ft.com/stream/brandId/NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz?format=rss

https://next.ft.com/stream/brandId/NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz.json
=>
https://next.ft.com/stream/brandId/NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz?format=json

The logic we have that looks at the `accept` header should be unaffected by this change.

**Comment by i-like-robots** [comment]
+1

**Comment by matthew-andrews** [comment]
i think this is fixed now? @i-like-robots

**Comment by i-like-robots** [comment]
Yep. We still support the dot extensions. I assume we need to remove those and add a redirect?

**Comment by matthew-andrews** [comment]
i think we could probably redirect them through in `next-redirector`

`/(.*).(json|rss)` => `/$1?format=$2`

**Comment by i-like-robots** [comment]
yep yep
