### ISSUE TITLE
Using stickies on other streams

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-stream-page#932]
The newsroom wants to reuse the Brexit 'stickies' feature on the page for the [UK Budget stream](https://next.ft.com/stream/topicsId/YmRlZTE5ZTAtNjMzMS00OGIxLTk5ZWEtMGI5YmY4NzViYmVi-VG9waWNz) in 2 weeks. ...any thoughts?

If we start adding stickies to other streams, I'm thinking the transformation config (currently in [profiles.js](https://github.com/Financial-Times/next-stream-page/blob/0ab95c980095821dbe49133926fc0ac5024bebab/server/config/profiles.js)) should probably come from a polled Bertha sheet, rather than requiring a code deployment for any change... something like:

listid | streamid | index | style
----|-----|-----|-----
7f12a510-bf62-11e5-9fdb-87b8d15baec2 | NDdiMzAyNzctMTRlMy00Zjk1LWEyZjYtYmYwZWIwYWU2NzAy-VG9waWNz | 0 | quintet
305def14-b3a1-11e5-8358-9a82b43f6b2f | NDdiMzAyNzctMTRlMy00Zjk1LWEyZjYtYmYwZWIwYWU2NzAy-VG9waWNz | 7 | list

or am I thinking about this the wrong way?

cc @matthew-andrews @i-like-robots @andygnewman @ironsidevsquincy

**Comment by matthew-andrews** [comment]
this feels like a good next step +1.

**Comment by callumlocke** [comment]
But I'm wondering how this would work just for a single transform. The current profiles architecture doesn't really allow for that.

I'm wondering if the whole profiles module should be replaced by one big polled Bertha sheet that links up streamIds to their various transform configs...? i.e. the sheet would include all of fastft's transforms, etc.

**Comment by matthew-andrews** [comment]
hmm, i see.  why not just stick with hard coding for a little bit longer.  when it gets unmanageable then we can build proper tooling…?

**Comment by i-like-robots** [comment]
100% for getting the hard coded configs out _but_ I don't think Bertha is much of an improvement - as you say, spreadsheets are hard to translate to code.

Reminds me of https://github.com/Financial-Times/next-stream-page/issues/843 =]

**Comment by callumlocke** [comment]
yep. the only obvious way I can see it working (what with some of the transforms requiring configuration) is to express them as JSON objects in the spreadsheet:

https://docs.google.com/spreadsheets/d/1dW1GbddJoqPqZj7ALkJgFp3Tunzvhn1qqzrhZ_mZ48Q/edit#gid=0

...which feels horrible.

> why not just stick with hard coding for a little bit longer. when it gets unmanageable then we can build proper tooling

I think that sounds sensible. @kavanagh?

**Comment by kavanagh** [comment]
The idea of the spreadsheet is for Editorial peeps to be able to simply wire stuff up lists to . Definitely don't expose this much config.

Also, what you have in there is implementation detail that could easily change. For example the midriff and the sticky stories are made to seem like one component that can be positioned in different places by setting an index. That seems wrong: their current similarities (rendering a list from the List API) are accidental.

Isn't the idea of transforms to augment a stream's model from the norm. What we are suggesting is to make sticky stories part of the norm, i.e pre-transform.

I think you should work towards something that is safer to expose to Editors. For now, two spreadsheets

1. Sticky stories sheet of 2 columns: Topic ID, List ID
2. Midriff sheet of 2 columns: Topic ID, List ID

Decide on a standard/default way to handle entries in each of those spreadsheet. Reserve transforms for overriding stuff. Hide this config or any kind of brittle schema away from non-developers.






_ps Bertha's `..yml` is better than `..json`._
