### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#980]
For section pages with editorially or otherwise curated content we believe pagination _may_ disappear, they will be like mini front pages for their topics.

However for blogs and chronological streams such as FastFT this isn't the case and pagination is a feature.

_However_ with the dynamic nature of some of these streams (filters, live updates) the pagination must be dynamic too, right? Currently this is not the case and it makes things weird.

**Comment by matthew-andrews** [comment]
> For section pages with editorially or otherwise curated content we believe pagination will disappear, they will be like mini front pages for their topics.

We can't keep pagination for the curated streams?  First page special, subsequent pages the raw feed?

**Comment by i-like-robots** [comment]
I think pagination should be considered like any other stream component. Does this page have pagination? Tick

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/next-stream-page/pull/985
