### ISSUE TITLE
Stream IDs are sometimes over-escaped, can change how the page renders

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-stream-page#995]
This is the correct URL to the US Election 2016 stream page:

https://next.ft.com/stream/sectionsId/N2UxNTM3MzItNWNlZC00MDc5LWI3ODUtYWNmZDA2YjE0MWE2-U2VjdGlvbnM=

...but it's possible to end up at a version where the `=` has been escaped to `%3D`:

1. Go to the US & Canada stream: https://next.ft.com/us
2. Scroll down until you find a "US Election 2016" tag on the left
3. Click it

The link takes you here:

https://next.ft.com/stream/sectionsId/N2UxNTM3MzItNWNlZC00MDc5LWI3ODUtYWNmZDA2YjE0MWE2-U2VjdGlvbnM%3D

And that page looks completely different (it's missing our IG stuff) probably because it doesn't match correctly.

**Comment by matthew-andrews** [comment]
hmm, my preference would be to find the places we're over encoding and fix them there…  Also this will get better as we have more and more vanities…

I'll set one up for the us election page now.

**Comment by callumlocke** [comment]
Agreed

A vanity would solve our immediate problem with the US election stream, thanks

**Comment by matthew-andrews** [comment]
actually it didn't … the broken URL is still broken :-/
https://next.ft.com/stream/sectionsId/N2UxNTM3MzItNWNlZC00MDc5LWI3ODUtYWNmZDA2YjE0MWE2-U2VjdGlvbnM%3D

that dodgy over-encoded thing might need tracking down.  if you can't find it i don't mind having a look later this week as part of my bug duty

**Comment by callumlocke** [comment]
do you think the double-encoding is likely to be a bug in the stream app, or could it be something elasticsearch-related?

**Comment by matthew-andrews** [comment]
hmm i thought the stream app, but could be either actually

**Comment by matthew-andrews** [comment]
i wonder if it's react.
